:facebook:
    :username: raykubot@chat.facebook.com
    :password: bghtyu123
    :accesstoken: AAAB3EIZBtPSkBALxoVyNobQqiTTQAbWt6kFPzGhXFpGcD9s6EwIXmmHIW1qujdABeBluXOzYk9sn6kVxUbcNq6uR2ZAYbLutZBhhABFkgZDZD
    :appid: 130913013677353